### PR TITLE
Several modifications to make it build with master branch of QTC

### PR DESCRIPTION
**Pull request by jeandet**
This are just quick tweaks to make this plugin compatible with current master branch of QTC.

### CODE REVIEW

**Comment by textshell** [comment]
Thanks.

As we later want to get this plugin into upstream qtcreator we need to make sure this paperwork for contributing to Qt is in place.
For the record, did you agree to the [contributor agreement](https://www.qt.io/legal-contribution-agreement-qt) regarding contributions to Qt and are submitting this as a contribution to be submitted to The Qt Company and/or the Qt Project? (Also to make it easier to match this to gerrit later, what is your gerrit user name?)

**Comment by jeandet** [comment]
I already signed the CLA and my Qt nickname is ajeandet.

**Comment by textshell** [comment]
Great. We'll merge this when we are ready to switch development to 4.8.x as base.

**Comment by trilader** [comment]
Thanks for the PR. We've not merged this directly as we've skipped directly from 4.7 to 4.9 beta and used the applicable part of your changes when doing the update.

**Pull request closed without merging**
